spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/spring_todo
    driverClassName: org.mariadb.jdbc.Driver
    username: $DB_USER
    password: root
#  jpa:
#    database: MYSQL
#    hibernate.ddl-auto: update


#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2.console.enabled: true

#
#  security:
#    user:
#      name: takumi
#      password: takumi  

#spring.datasource.url=jdbc:mysql://localhost/testdb
#spring.datasource.username=username
#spring.datasource.password=password
#spring.datasource.driverClassName=com.mysql.jdbc.Driver